name: Docker Build and Push

on:
  push:
    branches: ["master", "develop"] # Added 'main' as a common production branch
  pull_request:
    branches: ["master", "develop"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Dockerfile and Tag
        id: vars
        run: |
          # Default to production settings
          DOCKERFILE_TO_USE="./Dockerfile.prod"
          IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/dockerreact:latest"

          # If on 'develop' branch, use development Dockerfile and tag
          if [[ "${{ github.ref_name }}" == "develop" ]]; then
            DOCKERFILE_TO_USE="./Dockerfile.dev"
            IMAGE_TAG="${{ secrets.DOCKERHUB_USERNAME }}/dockerreact:dev-latest"
          fi
          echo "dockerfile_to_use=$DOCKERFILE_TO_USE" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ steps.vars.outputs.dockerfile_to_use }}
          push: true
          tags: ${{ steps.vars.outputs.image_tag }}
